
services:
  db:
    image: mariadb:11
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-wp}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wp}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "mariadb", "-u", "root", "-p${DB_ROOT_PASSWORD:-root}", "-e", "SELECT 1;"]
      interval: 5s
      timeout: 5s
      retries: 20

  wordpress:
    image: wordpress:php8.3-fpm
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER:-wp}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wp}
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
    volumes:
      - ./wp:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/zz-custom.ini
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  web:
    image: nginx:alpine
    depends_on:
      - wordpress
    ports:
      - "${WEB_PORT:-8080}:80"
    volumes:
      - ./wp:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  mailhog:
    image: mailhog/mailhog
    ports:
      - "${MAILHOG_PORT:-8025}:8025"

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
    ports:
      - "${PMA_PORT:-8081}:80"

volumes:
  db_data:
