name: CI

on:
  push:
  pull_request:

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3' ]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
      - run: composer install --prefer-dist --no-progress
      - run: vendor/bin/phpcs
      - run: vendor/bin/phpstan analyse

  js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || pnpm install
      - run: npm run build || pnpm build
